### ISSUE TITLE
Resources::version_info() hardcodes language code as 1033

### ISSUE THREAD

**Issue by Ortham** [CasualX/pelite#134]
Apparently there doesn't need to be a US English VERSIONINFO resource - I've come across a DLL that only has a version info resource for language 1049 (Russian). This is an unnecessary problem if you're only after the VS_FIXEDFILEINFO structure, which is language-independent and doesn't require a language code to be provided to [VerQueryValueW](https://docs.microsoft.com/en-gb/windows/desktop/api/winver/nf-winver-verqueryvaluew).

It would be useful to have a few methods (names are provisional, I'm happy to bikeshed them):

- `Resources::fixed_version_info() -> Option<&'a VS_FIXEDFILEINFO>` for when you only want the language-independent bit
- `Resources::first_version_info() -> Result<VersionInfo<'a>, FindError>` for when you don't know or care what language's version info to get
- `Resources::localised_version_info(language: u16) -> Result<VersionInfo<'a>, FindError>` for when you know what language to try for

Alternatively, the latter two could be replaced by a method that returns a collection of all VersionInfo resources and leaves it up to the user to pick which to use. That would also make it easier to inspect what languages have VersionInfo structures available.

(The language for Resources::manifest() is also hardcoded to 1033, presumably that can have the same issue, but I haven't looked into it.)

**Comment by CasualX** [comment]
Ah, I must admit I'm not too familiar with how the language parameter plays into here. I kind of assumed there was only ever one version info (it doesn't make much sense otherwise).

I would like to match the intended semantics of the WinAPI functions both to avoid bike shedding and to create the API more intuitive for people familiar with that API. But I'm afraid I have no idea how those WinAPI functions are supposed to be used. Notice that none of them accept a language parameter.

As for the application manifest, same deal. I don't understand window's actual semantics in case of non-1033 manifest or even what if there are multiple manifests (for a few different languages), what is the expected behaviour here?

In terms of actual API provided by pelite I would like the convenience methods at the top level `Resource` object to match behaviour of windows as much as possible and leave the rest to the user themselves using the API available: `find_resource` and load the result in the `VersionInfo` parser.

**Comment by Ortham** [comment]
> Notice that none of them accept a language parameter.

`VerQueryValue` does accept a language, as part of its `lpSubBlock` value, see [here](https://docs.microsoft.com/en-gb/windows/desktop/api/winver/nf-winver-verqueryvaluew#stringfileinfolang-codepagestring-name).

> what is the expected behaviour here? 

I've got no idea what Windows does if there are multiple version resources for different languages - I was looking around for information on it, but couldn't find anything conclusive. All I know is that Explorer will display the version info for a DLL with only Russian strings as if they were US English, so Pelite failing in the same case is unexpected.

If nothing else, I think that it should be documented that the `version_info()` function is looking for US English strings only, and will fail if they aren't found. (The same probably applies to the `manifest()` function.)

> I would like the convenience methods at the top level Resource object to match behaviour of windows as much as possible

With WinAPI, you call `GetFileVersionInfo` to get the version info structure, then:

- if you only want the fixed version info, you'd only call `VerQueryValue` with a `lpSubBlock` value of `\`.
- if you want a string value and you knew what language you wanted, you'd call `VerQueryValue` with a `lpSubBlock` value of the form `\StringFileInfo\lang-codepage\string-name`. If that language doesn't have a block of strings, then you'd call `VerQueryValue` with a `lpSubBlock` value of `\VarFileInfo\Translation` to get what language blocks exist and pick one to call with `\StringFileInfo\lang-codepage\string-name` again.

In Pelite, `Resources::version_info()` is similar to `GetFileVersionInfo`, but it only gets the version strings for US English and fails if they aren't present. To be analogous to WinAPI, I'd say:

- `Resources::version_info()` should get a `VersionInfo` that allows access to all languages' strings, instead of just US English strings.
- `VersionInfo::query_value()` should have a language codepage parameter.
- `VersionInfo::to_hash_map()` would need to be changed to either be language-specific or to return some kind of multimap to allow keys to have multiple values. I'm not sure about this one.
- `VersionInfo` should also have a method that gets the available language codepages, e.g. `VersionInfo::language_code_pages()-> Vec<u32>` or similar (instead of `u32` a `LanguageCodePage` wrapper type that has methods to get the high and low `u16`s might be useful).

I don't know how feasible it is to implement though.

**Comment by CasualX** [comment]
With my work on extracting icons and cursors I took a cursory look at this again.

I've changed how Resources::version_info works by just taking the first RT_VERSION language it finds. This kinda blows but it should... 'work' I guess? You can use the new `Resources::find_resource_ex` and manually construct a `VersionInfo` if you know the specific language.

A single version info block has lang parameters _everywhere_. Are these used in practice? Meaning does a single version info contain information in multiple languages? What would it mean if there are different version info blocks at the resource level (but within each version info block the language is consistent)? Eg. [this stackoverflow question](https://stackoverflow.com/questions/47441124/how-to-traverse-a-multi-language-version-resource) has an example.

From looking around I get the impression that different language resources are in different 'mui' binaries...

If you want to inspect the detailed information use `for_each_string` and extract what you need is the best I can offer right now.

**Comment by Ortham** [comment]
A while ago I tried implementing something like what I suggested above, but it turned out to be pretty complicated and I all I personally needed was to get the first language, whatever it was, so I didn't pursue it.

With your change to `Resources::version_info()`, my original issue is resolved without having to care about the structure of the resources so much, so thanks!

**Comment by CasualX** [comment]
Hey @Ortham , I've further refactored the VersionInfo API in #194 it should now match semantics of VerQueryValue much closer.

**Comment by Ortham** [comment]
Thanks, that turned this (from before your change last month):

```
let bytes = resources
    .find_dir(Path::new("/16/1"))?
    .entries()
    .next()
    .ok_or(FindError::NotFound)?
    .entry()?
    .data()
    .ok_or(FindError::UnDirectory)?
    .bytes()?;

VersionInfo::try_from(bytes)
    .map_err(FindError::Pe)?
    .query_value(&"ProductVersion")
    .map(String::from_utf16_lossy)
```

into this:

```
resources.version_info()?
    .translation()
    .and_then(|translations| translations.first())
    .and_then(|translation| version_info.value(*translation, "ProductVersion"))
```

which is a lot nicer! I think it would be even better if I could write that as:

```
resources.version_info()?
    .translations()
    .first()
    .and_then(|translation| version_info.value(*translation, "ProductVersion"))
```

I.e. instead of having `translation()` return an optional slice, rename it to `translations()` and where the Option would be `None`, return an empty slice instead. I personally think it's a bit redundant to return an optional collection, though in this case I know why it's done like that. A singular method name possibly returning multiple translations also feels a bit odd, though the Option wrapping them is singular, so I guess that makes sense. Both minor things though, thanks! 👍
