### ISSUE TITLE
Static array is full of zeroes

### ISSUE THREAD

**Issue by olson-dan** [CasualX/pelite#180]
I'm not certain this is a problem with the library, so apologies if this is a waste of your time.  This library is really well put-together, but I'm having one significant problem.

I'm reading an array out of a PE with an RVA I got from the `pdb` crate.  I've marked the structure as `[repr(C)]` and `POD`.  The code is something like this:

```
    let file = FileMap::open(filename)?;
    let pe_file = PeFile::from_bytes(&file)?;

    // ...

    for sym in &pdb.symbols {
        let fields = pe_file.derva_slice::<myStruct_t>(sym.rva, sym.count)?;
        println!("{:?}", fields);
    }
```

The element is something like 40 bytes and the array has 2600 elements.  After 500-or-so elements I start getting all zeroes.  Prior to that the data is correct.

I'm wondering if there's something big that I'm missing here.   I get identical results if I do any of the following:
- Switch to `ImageMap` and `PeView` instead of `PeFile`.
- Read the file directly using `std::fs::read`.
- Read each element manually by incrementing the rva by the structure size.
- Switch from an optimized executable to a debug executable.

I've debugged into `derva_slice` and everything looks ok... the array fully fits into the section's memory.  I just get zeroes for most of the data.

Edit: Now I've also looked at it in CFF explorer and can confirm that the zeroes are there, which further exonerates the library, but it's still unclear where the data is coming from when the PE is actually loaded.

Any ideas what's going wrong?

**Comment by CasualX** [comment]
Thanks for coming by! Getting any kind of feedback of how pelite is used by third parties will never be a waste of time.

Runtime initialization is indeed a pain when doing static analysis. In the past I've tried to [half-ass execute](https://github.com/CasualX/pelite/blob/master/examples/csgo/recvtables.rs#L130) instructions which simply write to global memory and found it... lacking.

I've thought about partially loading the target executable and... simply running the initialization code (intercepting required imports so no other dependencies are needed) but never got to really experiment with it.
