### ISSUE TITLE
Extract files?

### ISSUE THREAD

**Issue by cyberpunkbln** [CasualX/pelite#181]
Hello,

can anybody say me how i can extract files from an exe with this crate? I want to extract the files that are in /.rsrc included. I need only to copy the files like an unpacker or receive an ImageBuffer.

thx

**Comment by CasualX** [comment]
If you're just interested in looking at the resource files, I made a WASM web app that may help you out:

https://casualhacks.net/pekit/

Pick the file you want, click the Resources tab and download the resources you want.

**Comment by cyberpunkbln** [comment]
@CasualX cool app thx, but i want it directly in my Rust-Project a possibility to iterarte over an PATH-like modul that i can receive the bytebuffer or a possibility to direct save the buffer as an file. Such your pekit as an pure rust-safe code.

The crate ico and the crate image has not the possibility to extract icons from an exe directly and i hoped i can use your crate for this simple need.

Like a wrapper where i can extract the icons from .rsrc to an imagebuffer an convert this buffer to an ico/image-Buffer.

**Comment by CasualX** [comment]
After some research I found that icons are stored a little bit more complex inside PE resources, the ICO header and its pixel data are split between group icons and icons.

I will take some time to figure out how to reassemble them.

**Comment by cyberpunkbln** [comment]
@CasualX Thanks for the time. This will definitivly expand the rust crate economy with an cool Feature.

At the moment i use the 7z binary to extract the .rsrc/ICON/* directory into an temp-dir, iterate over the temp-dir .icos and receive the latest .ico to work with it in crate image. Like the most programs under windows:).

**Comment by CasualX** [comment]
I made a branch where I attempt to parse group icons back into full ICO files: https://github.com/CasualX/pelite/tree/features/group_icon

You can see the diff here: https://github.com/CasualX/pelite/commit/95fb79f116059f8164ac7519872870161467aca9?diff=unified

Look at the example to use this code. I will try clean this up and finish it for inclusion in pelite but that may take some more time.

**Comment by cyberpunkbln** [comment]
@CasualX wonderful, it will be great if you can made a small example for this in den readme or here? or made a small example in the example dir? thx

**Comment by CasualX** [comment]
I have an example [here](https://github.com/CasualX/pelite/blob/features/group_icon/examples/extract-icons.rs).

Note that this is 1. an example and 2. not merged into master. In order to try it out you need to add a git dependency (on the right branch) or just clone the repo.

If you want to try it out locally: `git clone https://github.com/CasualX/pelite.git && cd pelite && mkdir "DEST_FOLDER" && cargo run --example extract-icons --release -- "DLL_PATH_HERE" "DEST_FOLDER"`

For testing I tried `set DLL_PATH_HERE=C:\Windows\System32\shell32.dll` and `set DEST_FOLDER=Icons` which seems to correctly dump the icons stored in shell32.dll

I'm going to add support for cursors as well (which is basically the same as icons) and see if I can get it merged. It'll take even more time before you'll see this code on crates.io.

**Comment by cyberpunkbln** [comment]
@CasualX Perfect thx, i try it in the next times, when i clean up my application.

Cargo has the ability to change the branch in the dependencies part?

**Comment by CasualX** [comment]
Cargo is awesome! See [the docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).

```
pelite = { git = "https://github.com/CasualX/pelite.git", branch = "features/group_icon" }
```

Note that cratesio won't allow such deps and at some point this branch will disappear as it is merged in master. When that happens on `cargo update` simply remove the branch specifier.

Also I forgot to specify you need to `git checkout features/group_icon` in the example I wrote above.

**Comment by cyberpunkbln** [comment]
@CasualX Functioned perfectly. thx.

**Comment by cyberpunkbln** [comment]
@CasualX Some additional question: Do you have a tip how i can convert &content to an imagebuffer for crate image::DynamicImage::ImageRgba8 ??

**Comment by CasualX** [comment]
ICO files contain multiple images, for which the image crate seems to have an [ICODecoder](https://docs.rs/image/0.21.1/image/ico/struct.ICODecoder.html). The ICO files in SHELL32.DLL seem to also contain PNG images which you can decode with [PNGDecoder](https://docs.rs/image/0.21.1/image/png/struct.PNGDecoder.html).

I've updated the [example to extract just the PNG images out of the icons](https://github.com/CasualX/pelite/blob/features/group_icon/examples/extract-icons.rs#L31-L40).

You can see how you iterate over the ICO entries and inspect the associated image to see if it starts with the [PNG magic bytes](https://en.wikipedia.org/wiki/List_of_file_signatures).

**Comment by cyberpunkbln** [comment]
@CasualX Thx for the example, very usefull.

Do you mean ICODecoder::new(&content) is the right way? In the past i have used crate ico and this have an rgba_data() function for her decode and this buffer i import in crate images with DynamicImage::ImageRgba8?

**Comment by CasualX** [comment]
I am unfamiliar with the image and ico crates, so I can't provide much support. From reading the docs the image crate wraps the ico crate for you.

Using the ICODecoder as you have shown looks right to me. An alternative is to look for the PNG images and read those instead.

Further processing requires following information provided by the image crate:

```rust
let mut contents = Vec::new();
group_icon.write(&mut contents).unwrap();

let ico_decoder = ICODecoder::new(&contents).unwrap();
let image = ico_decoder().read_image().unwrap();
```

It should be something like that, from what I gather from the image crate.

**Comment by cyberpunkbln** [comment]
@CasualX Perfect thx, that i will try in the next hours:). The notepad++.exe took me a lot of time, why he has dozens of creepy icons and why i have (at this state) no terminal-ui and i make all with automatic allgorythmens i choose the vector-buffers (&content.len()) which is the highest and hope for other exe files that he have the standard-group-icon (one file, many entries) or only one:).

Very great the rust community has been extended valueable.

Now i'm search for an library that can handle windows shortcuts (.lnk).
