### ISSUE TITLE
Windows and pelite differ in handling of weird binaries.

### ISSUE THREAD

**Issue by Lucius-Q-User** [CasualX/pelite#198]
The attached binary has the size of the resource directory set to 350720, while it's .rsrc section is only 340996 bytes long (virtual size). Windows is okay with this file, and is capable of loading and running it correctly, while pelite returns Error::Bounds

[HxD.exe.zip](https://github.com/CasualX/pelite/files/3527424/HxD.exe.zip)

**Comment by CasualX** [comment]
Thanks for the report!

Indeed HxD's resource directory is just plain out of bounds: The `.rsrc` section's raw size is `0x53600` and its virtual size is `0x53404` yet the directory entry claims `0x55a00` bytes.

Furthermore the virtual SizeOfImage of the entire HxD.exe is `0x684000` which matches the extend of the `.rsrc` section (rounded up to nearest 4K): `0x630000 + 0x53600 = 0x683600`. This looks like the resource directory entry is definitely out of bounds.

Finally the file is `0x671800` bytes and claims the resource directory's file offset ends at `0x61e200 + 0x53600 = 0x671800`. Exactly matching the file size.

The number in the resource directory is plain wrong. However evidently Windows has no issue reading information from its resources.

How should pelite handle this?

**Comment by Lucius-Q-User** [comment]
There are three possible behaviors in this case: 

1. The file is malformed and should be rejected, therefore keeping the current behavior.
2. While some parts of the file are invalid, windows (which we consider to be the reference implementation of a PE parser) doesn't seem to mind, and the file is in general salvageable, therefore the OOB check should be pushed down the road, when the bytes for out of bound content are actually being read.
3. Introduce a strict/sloppy switch that allows the user to select the desired behavior.

My use-case (extracting icons) needs either the 2nd or the 3rd option, but it is possible that some other users of pelite depend on it following option 1 for input consistency checking.

**Comment by CasualX** [comment]
For pelite 'what is a valid PE file' means "whatever Windows accepts and is reasonable".

I don't mind accepting PE files which don't actually run (not that big of a deal), I don't mind rejecting certain tiny PE files which heavily overlap their PE headers to decrease size (unreasonable, but I may try).

In this case I'm considering towards 2. pushing back the OOB check. The `Resources<'a>` struct holds a reference to the underlying bytes, this necessarily means an OOB check must already have happened. So instead I propose to clamp the resource directory's size.

I've included a tentative PR to address the issue. Let me know if this solves your problem.

**Comment by Lucius-Q-User** [comment]
Confirming that the PR fixes the issue with the HxD file
