### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Dopepigeon** [CasualX/pelite#202]
Hey could you make a readme in the apex example and how to use it, it would be nice since i have very less knowledge on Rust :)

Kind Regards Dopepigeon

**Comment by CasualX** [comment]
Sure, I'll leave a note.

This tool is just a static analyzer, it requires that you first (successfully) dump the Apex Legends executable (it is encrypted on disk and decrypted at runtime).

Once you have a dumped image you run `cargo run --example apex --release -- %APEX_LEGENDS_DUMP% > examples/apex/stdout.md` where `APEX_LEGENDS_DUMP` is the file path of your dump of the Apex Legends executable.

Then sit back while it analyzes and writes a (markdown formatted) report.

**Comment by Dopepigeon** [comment]
Okay i dumped it with dbg64 so that should be fine right?

**Comment by CasualX** [comment]
Probably? Try it out and if it doesn't work let me know.

**Comment by Dopepigeon** [comment]
Okay thanks i will try it out as soon as i am home :)

**Comment by Dopepigeon** [comment]
It worked thanks :)
