### ISSUE TITLE
no `pattern_attribute` in the root

### ISSUE THREAD

**Issue by FiYHer** [CasualX/pelite#244]
How can I use this to get the offset of APEX,
 I'm sorry I don't understand rust, there are more than 70 errors when trying to execute ^_^

**Comment by CasualX** [comment]
Hi, I'm aware that I broke the 0.8 version of pelite. You can manually change to 0.9 or simply pull again from the apexbot repo as I've pushed some changes which fix the offset dumper.

**Comment by FiYHer** [comment]
Thank you very much, I used the v0.9 version to compile perfectly
