### ISSUE TITLE
Writing to imports

### ISSUE THREAD

**Issue by iraizo** [CasualX/pelite#251]
My current goal is to fix the imports, replacing the pointer to the imported function in the module i want to map from the process iat.
The problem is pelite only has a way to get the imports and not write them since i want to later on write them into the pefile, convert them back to an byte array and then overwrite the pe header. 

Is there a manual way to do this?

**Comment by iraizo** [comment]
i guess calling `.image()` would solve having the byte array, but not how to actually write the imports

**Comment by CasualX** [comment]
Unfortunately this use case isn't really supported due to pelite using shared borrows everywhere.

The best alternative is to gather a set of 'todo' modifications and after destroying all pelite related objects to 'apply' these modifications when there's no more pelite shared borrows active.

**Comment by iraizo** [comment]
Could you give me an example for this? I dont really understand it due to not using rust for a long time yet
