### ISSUE TITLE
VersionInfo.fixed() return None while version info does exist

### ISSUE THREAD

**Issue by wangjia184** [CasualX/pelite#254]
[BE.Essential.dll.zip](https://github.com/CasualX/pelite/files/8854120/BE.Essential.dll.zip)

Please check this file,  it is a file complied by .NET Core targeting linux x64. It is a PE file and you can check its file version in Windows explorer.  But pelite cannot retrieve its version.

**Comment by CasualX** [comment]
I did a little digging and found the exact location where parsing goes wrong: https://github.com/CasualX/pelite/blob/1efbb8ee9af31ff6151fb2539b1ea44d4b005cdc/src/resources/version_info.rs#L571

I vaguely remember being horrified at the spec (length can be in bytes or in words) and unsure what to do, this may take some time to figure out sorry.

Parsing goes wrong figuring out the first structure of the version info, here's the msdn docs: https://docs.microsoft.com/en-us/windows/win32/menurc/vs-versioninfo

**Comment by wangjia184** [comment]
@CasualX  can a new version be released to crate.io?

**Comment by CasualX** [comment]
soon (tm)

**Comment by CasualX** [comment]
Update published
