### ISSUE TITLE
32-bit linux build broken

### ISSUE THREAD

**Issue by h33p** [CasualX/pelite#261]
It appears that `IMAGE_DYNAMIC_RELOCATION64` size constraint is violated on 32-bit Linux environments. See the error in our CI: https://github.com/memflow/memflow-qemu/runs/7271610781. Could this be an alignment issue? Or should size of an array be checked instead, like done [in memflow](https://github.com/memflow/memflow-win32/blob/main/src/offsets/offset_table.rs#L45)?

**Comment by CasualX** [comment]
From this [random person's copy](https://github.com/tpn/winsdk-10/blob/9b69fd26ac0c7d0b83d378dba01080e93349c2ed/Include/10.0.16299.0/km/ntimage.h#L1681-L1685) of what appears to be win10 sdk it appears I just got the definition wrong.

Notice this block is surrounded by `#include "pshpack1.h"`, that sets the struct alignment to 1.

**Comment by CasualX** [comment]
This problem only crops up now because in 0.9.1 I assert the sizes of structs at compile-time, where before they would only be checked at test time.
