### ISSUE TITLE
Add .rustfmt.toml to repo + format code

### ISSUE THREAD

**Issue by Ben-Lichtman** [CasualX/pelite#269]
I'd like to contribute to this project, however it seems like the style is mostly ad-hoc and rustfmt is not being used for the most part?

I propose adding a .rustfmt.toml to the root of the project to ensure that contribution style is consistent, then running `cargo fmt` on the repo to format the code.

I've tried to come up with a `.rustfmt.toml` which is minimally imactful while still providing some benefits:

```toml
edition = "2021"
hard_tabs = true
match_block_trailing_comma = true
control_brace_style = "ClosingNextLine"
```
Unfortunately this still leads to a large number of changes due to many small adjustments.

More settings can be found [here](https://rust-lang.github.io/rustfmt/?version=v1.5.2)

One other potential issue is the lack of a setting for preserving aligned spaces such as 
```rust
const SOME_LONG_NAME: i32       = 5;
const SHORT: i32                = 6;
```
This patten is found in a few places, especially `src/image.rs`
In this case if you want to preserve the nice alignment there are a few options:
- Add `#[rustfmt::ignore]` annotations to each line that you want to preserve formatting
- Move the aligned variables into an inline module and mark it as `#[rustfmt::ignore]`
- Add `#![rustfmt::ignore]` to the top of the file to avoid formatting the whole thing

**Comment by Ben-Lichtman** [comment]
The other option is to disable rustfmt project-wide with [disable_all_formatting](https://rust-lang.github.io/rustfmt/?version=master&search=disable#disable_all_formatting) in the .rustfmt.toml, though I'd suggest that it's better to pick a suboptimal style rather than ad-hoc style chosen by contributors

**Comment by Ben-Lichtman** [comment]
I would PR this, but it would be difficult to review due to the large number of changes, so I'll leave it up to the maintainer to push a version with `cargo fmt` run on it

**Comment by CasualX** [comment]
Thanks for your consideration! I've been working on implementing a rustfmt policy that I can stomach.

I'm not a fan of autoformatters in general as they tend to make everything look consistently ugly.
But with some okay settings, a nightly rustfmt, refactoring some code and liberal application of `rustfmt::skip` I think I can make it work.

I'll try to get a PR up in a few more hours.

**Comment by CasualX** [comment]
Good lord I just noticed rustfmt rewrote everything to lf which conflicts with my windows checkout and usage of autocrlf setting... I'll try to keep going and get the repo to cleanly pass rustfmt but rustfmt is just not ready for actual usage...

**Comment by Ben-Lichtman** [comment]
You can adjust this with the newline_style setting

**Comment by CasualX** [comment]
I can confirm that this is not the case, all files changed by `cargo +nightly fmt` (idk if nightly matters here) are changed from crlf to lf. Look like it is an open bug in rustfmt: https://github.com/rust-lang/rustfmt/issues/4097

Some git magic later it's all fixed but these are the kind of rough edges that make confirm my biases against rustfmt 😛

**Comment by CasualX** [comment]
It took some time but it's there
