### ISSUE TITLE
Get &[u8] or Vec<u8>.

### ISSUE THREAD

**Issue by Paradist** [CasualX/pelite#272]
I want to get back &[u8] or Vec<u8> containing the `.exe` binary code from `pe` and then save that to a file..

```rust
let file = FileMap::open("./name.exe").unwrap();
let mut pe = PeFile::from_bytes(file.as_ref()).unwrap();
```

I tried:

```rust
pe.image()
```
But it produces a value 900 +- bytes larger than the original.

Help me, please.
Thank you in advance.

**Comment by Paradist** [comment]
And how can I edit the certificate, versions, and resources?

**Comment by CasualX** [comment]
This library is not designed to let you edit the file conveniently.


To get the original bytes, just go back to the original file:

```rust
let file = FileMap::open("./name.exe").unwrap();
let mut pe = PeFile::from_bytes(file.as_ref()).unwrap();
// Do things with pe...
let bytes = file.as_ref();
```

PeFile and friends just lightly wrap a &[u8], you are not meant to store these types long term (recreate them if necessary). Simply access the underlying storage.

FileMap is a readonly view over the file, so if you wish to modify the bytes you have to use std::fs::read to read the contents into a Vec<u8> then process that. After you have done your processing, collect all the edits you wish to make and apply them after the wrappers (like PeFile) are no longer used then save the resulting Vec<u8> back to disk with std::fs::write.
