### ISSUE TITLE
Missing exports in kernel32.dll

### ISSUE THREAD

**Issue by lexika979** [CasualX/pelite#277]
Hello,
first of all, thank you for providing this library. It's been of great use for me lately.
Unfortunately, i've seem to run into a issue, where when iterating the exported functions of kernel32.dll (32bit), some exported functions seem to be missing.

These seem to be:
HeapAlloc
HeapReAlloc
InitializeSListHead
SleepConditionVariableSRW
WakeAllConditionVariable
AcquireSRWLockExclusive
ReleaseSRWLockExclusive

Here is how I iterate the exports:
```
                            pe.exports()?
                                .by()?
                                .iter_names()
                                .filter_map(|result| match result {
                                    (Ok(name), Ok(export)) => export
                                        .symbol()
                                        .map(|symbol| (name.to_string(), base + symbol as u64)),
                                    _ => None,
                                })
                                .collect::<HashMap<_, _>>()
```

Am I doing something wrong?

**Comment by CasualX** [comment]
Exported symbols can be forwarded to another dll. Here with `.symbol()` you only get symbols implemented by kernel32.dll itself.

https://docs.rs/pelite/latest/pelite/pe32/exports/enum.Export.html#variant.Forward

There's another link for more information on how these work.

**Comment by lexika979** [comment]
Ah I see, didn't think about that - Thank you for the quick response!
