### ISSUE TITLE
Implement imphash

### ISSUE THREAD

**Issue by insanitybit** [CasualX/pelite#39]
One thing provided in the python `pefile` package is a get_imphash method.

https://github.com/erocarrera/pefile/blob/4c57c1443bb504281dcc00e1ddec9d62c5e39b35/pefile.py#L3824

This would be a great feature.

**Comment by CasualX** [comment]
I found this interesting article discussing get_imphash: https://www.fireeye.com/blog/threat-research/2014/01/tracking-malware-import-hashing.html

This seems like a very specific feature for a very specific use case which I don't think is appropriate for pelite.

That said making it easy to calculate imphash and eg. providing an example that does exactly that seems like a good idea.

**Comment by insanitybit** [comment]
Cool, yeah I think that makes sense - it's definitely very specific, but the primitives for implementing it seems relevant to the crate.

A separate crate that actually provides the implementation would probably be more reasonable.

**Comment by CasualX** [comment]
I've implemented a simplified version of this feature as an example.

Uses the default hasher and not trying to be fancy with imports.

```
> cargo run --example imphash -- C:\Windows\System32\msvcp140.dll
Import hash is 66182F54652495EE for "C:\\Windows\\System32\\msvcp140.dll".
```
